export const SET_PROPERTY_TYPES = 'SET_PROPERTY_TYPES'
export const SET_ENTITY_TYPES = 'SET_ENTITY_TYPES'
export const SET_ASSOCIATION_TYPES = 'SET_ASSOCIATION_TYPES';

export const FETCH_ALL_DATA = 'FETCH_ALL_DATA';
export const FETCH_ALL_DATA_SUCCESS = 'FETCH_ALL_DATA_SUCCESS';