export const SET_PROPERTY_TYPES = 'SET_PROPERTY_TYPES'
export const SET_ENTITY_TYPES = 'SET_ENTITY_TYPES'
export const SET_ASSOCIATION_TYPES = 'SET_ASSOCIATION_TYPES';

export const FETCH_ALL_DATA = 'FETCH_ALL_DATA';
export const FETCH_ALL_DATA_SUCCESS = 'FETCH_ALL_DATA_SUCCESS';

export const SELECT_PROPERTY_TYPE = 'SELECT_PROPERTY_TYPE';
export const SELECT_ENTITY_TYPE = 'SELECT_ENTITY_TYPE';
export const SELECT_ASSOCIATION_TYPE = 'SELECT_ASSOCIATION_TYPE';
export const SELECT_MODEL = 'SELECT_MODEL';

export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE'; //react-router-redux;