export const IS_FETCHING = 'IS_FETCHING'
export const SET_PROPERTY_TYPES = 'SET_PROPERTY_TYPES'
export const SET_ENTITY_TYPES = 'SET_ENTITY_TYPES'
export const SET_ASSOCIATION_TYPES = 'SET_ASSOCIATION_TYPES';